import { useState } from 'react';
import { useNavigate } from "react-router-dom";
import Adminside from "./adminside";
import './notifications.css';

function App() {
  const tickets = [
    {
      id: '#0001',
      status: 'new',
      title: 'How can I ensure that the content generated by the AI is plagiarism-free?',
      user: 'John Doe',
      timeAgo: '2 days ago'
    },
    {
      id: '#0002',
      status: 'active',
      title: 'Can the AI content generator create content in different languages?',
      user: 'Jane Smith',
      timeAgo: '3 days ago'
    },
    {
      id: '#0003',
      status: 'active',
      title: 'The content generated by the AI seems to be low quality. Can this be improved?',
      user: 'Sophie Davis',
      timeAgo: '3 days ago'
    }
  ]

  const [searchId, setSearchId] = useState('')

  return (
    <div className="notifications-container">
    <Adminside />
    <div className="notifications-wrapper">
      <div className="header-noti">
        <h1>Notifications</h1>
        <nav>
          <span>Feedback</span>
          <span className="separator">›</span>
          <span>Support Center</span>
        </nav>
      </div>

      <div className="stats">
        <div className="stat-box">
          <span className="stat-number red">08</span>
          <span className="stat-label">In queue</span>
        </div>
        <div className="stat-box">
          <span className="stat-number orange">03</span>
          <span className="stat-label">In Progress</span>
        </div>
        <div className="stat-box">
          <span className="stat-number blue">689</span>
          <span className="stat-label">All Tickets</span>
        </div>
      </div>

      <div className="controls">
        <div className="search-box">
          <input
            type="text"
            placeholder="Search by id"
            value={searchId}
            onChange={(e) => setSearchId(e.target.value)}
          />
        </div>
        <div className="show-entries">
          <span>Show</span>
          <select>
            <option>8</option>
            <option>16</option>
            <option>24</option>
          </select>
        </div>
      </div>

      <div className="tickets">
        {tickets.map((ticket) => (
          <div key={ticket.id} className="ticket-card">
            <div className="ticket-header">
              <span className={`status ${ticket.status}`}>{ticket.status}</span>
              <span className="ticket-id">Ticket id : {ticket.id}</span>
            </div>
            <h3 className="ticket-title">{ticket.title}</h3>
            <div className="ticket-footer">
              <div className="user">
                <div className="avatar"></div>
                <div className="user-info">
                  <div className="name">{ticket.user}</div>
                  <div className="time">Asked {ticket.timeAgo}</div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>  
    </div>
      
    </div>
  )
}

export default App